google:
  accessTokenEndpoint: https://www.googleapis.com/oauth2/v4/token
  userProfileEndpoint: https://www.googleapis.com/oauth2/v2/userinfo
  grantType: authorization_code
  clientId: [ id de cliente google ]
  clientSecret: [ secret de cliente google ]
  fields: email,name,family_name,given_name,id,verified_email

facebook:
  accessTokenEndpoint: https://graph.facebook.com/v3.2/oauth/access_token
  userProfileEndpoint: https://graph.facebook.com/v3.2/me
  grantType: fb_exchange_token
  clientId: [ id de cliente facebook ]
  clientSecret: [ secret de cliente facebook ]
  fields: id,name,email,first_name,last_name
  